# Generated by Django 5.1.3 on 2024-12-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='country',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
