# Generated by Django 5.1.3 on 2024-12-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_table', '0002_rename_country_member_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='member',
            name='phoneno',
            field=models.IntegerField(default=25),
        ),
    ]
